apiVersion: v1
kind: Service
metadata:
  name: ai-quantizer-hub-service
  labels:
    app: ai-quantizer-hub
spec:
  type: LoadBalancer
  selector:
    app: ai-quantizer-hub
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
